### ISSUE TITLE
Crash (segfault) in configure > controls for Keen 1 (Kubuntu 14.04)

### ISSUE THREAD

**Issue by fbcoder** [gerstrong/Commander-Genius#197] opened 2014-08-17 11:55 UTC
Start Cgenius, select Keen1 > Configure > Controls > Select one of the players. At this point there is an empty config window and it's not possible to go back. Clicking the arrow in the upper left corner or pressing left arrow key or ESC causes a segfault. This crash is reproducible on my machine.

As it does not seem possible to attach a crash report directly I made a screenshot of the stracktrace. If you need the whole apport crash file (about 2.2 MB) I can upload it to dropbox.

![cgenius_crash_stacktrace](https://cloud.githubusercontent.com/assets/3841469/3944456/853b34c8-2604-11e4-9054-a529e65e6f55.png)

**Comment by gerstrong** [comment] 2015-01-03 08:02
I was not able to reproduce this anymore, closing

**Closed by gerstrong** 2015-01-03 08:02 UTC
