### ISSUE TITLE
Could not successfully install Commander Genius - Modern Interpreter for the Commander Keen Games (Vorticon and Galaxy Games) (home/pi/RetroPie-Setup/tmp/build/cgenius/src/CGeniusExe not found)

### ISSUE THREAD

**Issue by nibio74** [gerstrong/Commander-Genius#340] opened 2018-05-02 11:05 UTC
This is the log:

Log started at: Wed  2 May 09:49:17 UTC 2018

RetroPie-Setup version: 4.4 (2d6962e)
System: Linux retropie 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux

= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'cgenius' : Commander Genius - Modern Interpreter for the Commander Keen Games (Vorticon and Galaxy Games)
= = = = = = = = = = = = = = = = = = = = =

/home/pi/RetroPie-Setup/tmp/build/cgenius /home/pi

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'cgenius' : Commander Genius - Modern Interpreter for the Commander Keen Games (Vorticon and Galaxy Games)
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --depth 1 --branch v2.2.2 "https://github.com/gerstrong/Commander-Genius.git" "/home/pi/RetroPie-Setup/tmp/build/cgenius"
Cloning into '/home/pi/RetroPie-Setup/tmp/build/cgenius'...
Note: checking out '124ee8a7047d25165656fb875019145fe9d8abd4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files:  10% (165/1529)   
Checking out files:  11% (169/1529)   
Checking out files:  12% (184/1529)   
Checking out files:  13% (199/1529)   
Checking out files:  14% (215/1529)   
Checking out files:  14% (225/1529)   
Checking out files:  15% (230/1529)   
Checking out files:  16% (245/1529)   
Checking out files:  17% (260/1529)   
Checking out files:  18% (276/1529)   
Checking out files:  18% (282/1529)   
Checking out files:  18% (284/1529)   
Checking out files:  19% (291/1529)   
Checking out files:  20% (306/1529)   
Checking out files:  21% (322/1529)   
Checking out files:  22% (337/1529)   
Checking out files:  23% (352/1529)   
Checking out files:  24% (367/1529)   
Checking out files:  25% (383/1529)   
Checking out files:  26% (398/1529)   
Checking out files:  27% (413/1529)   
Checking out files:  28% (429/1529)   
Checking out files:  29% (444/1529)   
Checking out files:  30% (459/1529)   
Checking out files:  31% (474/1529)   
Checking out files:  32% (490/1529)   
Checking out files:  33% (505/1529)   
Checking out files:  33% (509/1529)   
Checking out files:  34% (520/1529)   
Checking out files:  35% (536/1529)   
Checking out files:  36% (551/1529)   
Checking out files:  37% (566/1529)   
Checking out files:  38% (582/1529)   
Checking out files:  39% (597/1529)   
Checking out files:  40% (612/1529)   
Checking out files:  41% (627/1529)   
Checking out files:  42% (643/1529)   
Checking out files:  43% (658/1529)   
Checking out files:  44% (673/1529)   
Checking out files:  45% (689/1529)   
Checking out files:  46% (704/1529)   
Checking out files:  46% (711/1529)   
Checking out files:  46% (714/1529)   
Checking out files:  46% (715/1529)   
Checking out files:  47% (719/1529)   
Checking out files:  47% (732/1529)   
Checking out files:  48% (734/1529)   
Checking out files:  48% (737/1529)   
Checking out files:  48% (739/1529)   
Checking out files:  48% (740/1529)   
Checking out files:  48% (742/1529)   
Checking out files:  48% (744/1529)   
Checking out files:  48% (745/1529)   
Checking out files:  49% (750/1529)   
Checking out files:  49% (754/1529)   
Checking out files:  50% (765/1529)   
Checking out files:  51% (780/1529)   
Checking out files:  52% (796/1529)   
Checking out files:  53% (811/1529)   
Checking out files:  54% (826/1529)   
Checking out files:  55% (841/1529)   
Checking out files:  56% (857/1529)   
Checking out files:  57% (872/1529)   
Checking out files:  58% (887/1529)   
Checking out files:  59% (903/1529)   
Checking out files:  60% (918/1529)   
Checking out files:  61% (933/1529)   
Checking out files:  62% (948/1529)   
Checking out files:  63% (964/1529)   
Checking out files:  64% (979/1529)   
Checking out files:  65% (994/1529)   
Checking out files:  66% (1010/1529)   
Checking out files:  67% (1025/1529)   
Checking out files:  68% (1040/1529)   
Checking out files:  69% (1056/1529)   
Checking out files:  70% (1071/1529)   
Checking out files:  71% (1086/1529)   
Checking out files:  72% (1101/1529)   
Checking out files:  73% (1117/1529)   
Checking out files:  74% (1132/1529)   
Checking out files:  74% (1143/1529)   
Checking out files:  75% (1147/1529)   
Checking out files:  76% (1163/1529)   
Checking out files:  77% (1178/1529)   
Checking out files:  78% (1193/1529)   
Checking out files:  79% (1208/1529)   
Checking out files:  80% (1224/1529)   
Checking out files:  81% (1239/1529)   
Checking out files:  82% (1254/1529)   
Checking out files:  83% (1270/1529)   
Checking out files:  84% (1285/1529)   
Checking out files:  85% (1300/1529)   
Checking out files:  86% (1315/1529)   
Checking out files:  87% (1331/1529)   
Checking out files:  88% (1346/1529)   
Checking out files:  89% (1361/1529)   
Checking out files:  89% (1369/1529)   
Checking out files:  90% (1377/1529)   
Checking out files:  91% (1392/1529)   
Checking out files:  92% (1407/1529)   
Checking out files:  93% (1422/1529)   
Checking out files:  93% (1425/1529)   
Checking out files:  94% (1438/1529)   
Checking out files:  95% (1453/1529)   
Checking out files:  96% (1468/1529)   
Checking out files:  97% (1484/1529)   
Checking out files:  98% (1499/1529)   
Checking out files:  99% (1514/1529)   
Checking out files: 100% (1529/1529)   
Checking out files: 100% (1529/1529), done.
/home/pi
/home/pi/RetroPie-Setup/tmp/build/cgenius /home/pi

= = = = = = = = = = = = = = = = = = = = =
Building 'cgenius' : Commander Genius - Modern Interpreter for the Commander Keen Games (Vorticon and Galaxy Games)
= = = = = = = = = = = = = = = = = = = = =

-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.10 loaded.
-- Found SDL2_mixer: /usr/lib/arm-linux-gnueabihf/libSDL2_mixer.so (found version "2.0.0") 
-- Setting build type to 'Release' as none was specified.
-- Preparing the Build-System for Commander Genius
-- Setting SYSTEM_DATA_DIR to /opt/retropie/ports/cgenius/
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/arm-linux-gnueabihf/libSDL2main.a;/usr/lib/arm-linux-gnueabihf/libSDL2.so;-lpthread  
-- Using shared SDL Version 2 for Commander Genius
-- Using shared SDL Version 2 for Commander Genius
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.4m.so (found version "3.4.2") 
-- SDLIMAGE INCLUDE DIR /usr/include/SDL2
-- SDLIMAGE_LIBRARY /usr/lib/arm-linux-gnueabihf/libSDL2_image.so
-- Using shared SDL Version 2 for Commander Genius
-- CXX target GsKit cotired.
-- Boost version: 1.55.0
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.8") 
-- Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.38.0") 
-- SDLIMAGE INCLUDE DIR /usr/include/SDL2
-- SDLIMAGE_LIBRARY /usr/lib/arm-linux-gnueabihf/libSDL2_image.so
-- Using shared SDL Version 2 for Commander Genius
-- Internal Downloader: ON
-- CXX target engine_keen_galaxy cotired.
-- SDL2_LIBRARY = /usr/lib/arm-linux-gnueabihf/libSDL2main.a;/usr/lib/arm-linux-gnueabihf/libSDL2.so;-lpthread
-- SDL2IMAGE_LIBRARY = 
-- CXX target CGeniusExe cotired.
-- CG_VERSION = 
-- CPACK_PACKAGE_VERSION = 0.1.1
-- Build system is prepared. To Build the project just type "make"
-- If you want to create the installation package just type "make package" after you build the project
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/RetroPie-Setup/tmp/build/cgenius
[  0%] Generating CXX unity source GsKit/cotire/GsKit_CXX_unity.cxx
[  1%] Generating CXX prefix source GsKit/cotire/GsKit_CXX_prefix.cxx
[  1%] Generating CXX prefix header GsKit/cotire/GsKit_CXX_prefix.hxx
[  1%] Building CXX precompiled header GsKit/cotire/GsKit_CXX_prefix.hxx.gch
Scanning dependencies of target GsKit
[  1%] Building CXX object GsKit/CMakeFiles/GsKit.dir/base/CInput.cpp.o
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp: In function ‘TouchButton* getPhoneButtons(stInputCommand (*)[16])’:
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[0]), KLEFT, 0, 200, 80, 80}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
  };
  ^
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[4]), -1, 0, 160, 80, 40, true}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[2]), KUP, 80, 160, 80, 80}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[5]), -1, 160, 160, 80, 40, true}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[1]), KRIGHT, 160, 200, 80, 80}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[7]), -1, 160, 280, 80, 40, true}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[3]), KDOWN, 80, 240, 80, 80}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[6]), -1, 0, 280, 80, 40, true}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[8]), KCTRL, 240, 213, 80, 106}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[9]), KALT, 320, 213, 80, 106}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[10]), KSPACE, 400, 213, 80, 106}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[11]), KSHIFT, 400, 213, 80, 106}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[15]), KQUIT, 0, 0, 80, 53}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[12]), KENTER, 400, 53, 80, 53}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{(&(* InputCommand)[14]), KF1, 0, 53, 80, 53}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
/home/pi/RetroPie-Setup/tmp/build/cgenius/GsKit/base/CInput.cpp:1475:2: error: could not convert ‘{0, -10, 400, 0, 80, 53}’ from ‘<brace-enclosed initializer list>’ to ‘TouchButton’
GsKit/CMakeFiles/GsKit.dir/build.make:85: recipe for target 'GsKit/CMakeFiles/GsKit.dir/base/CInput.cpp.o' failed
make[2]: *** [GsKit/CMakeFiles/GsKit.dir/base/CInput.cpp.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'GsKit/CMakeFiles/GsKit.dir/all' failed
make[1]: *** [GsKit/CMakeFiles/GsKit.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
/home/pi
Could not successfully build cgenius - Commander Genius - Modern Interpreter for the Commander Keen Games (Vorticon and Galaxy Games) (/home/pi/RetroPie-Setup/tmp/build/cgenius/src/CGeniusExe not found).

Log ended at: Wed  2 May 09:56:22 UTC 2018
Total running time: 0 hours, 7 mins, 5 secs

Please help me, where is the problem?

**Comment by nibio74** [comment] 2018-05-06 13:36
Excuse my ignorance in linux, but how do I try your fork?

**Comment by nibio74** [comment] 2018-05-06 13:59
Done.

git clone git://github.com/gerstrong/Commander-Genius.git
cd Genius-Commader
mkdir -p CGeniusBuild
cd CGeniusBuild
cmake ../../Genius-Commander
make

Now I wait for the compilation.

**Comment by nibio74** [comment] 2018-05-06 16:32
Another error :-(

In file included from /home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.cpp:8:0:
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h: In member function ‘virtual void galaxy::CVarPlatform::_ZTv0_n120_N6galaxy12CVarPlatform9serializeER19CSaveGameController(CSaveGameController&)’:
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h:33:10: internal compiler error: Segmentation fault
     void serialize(CSaveGameController &savedGame);
          ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccA5tslK.out file, please attach this to your bugreport.
src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/build.make:638: recipe for target 'src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/ai/platform/CVarPlatform.cpp.o' failed
make[2]: *** [src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/ai/platform/CVarPlatform.cpp.o] Error 1
CMakeFiles/Makefile2:859: recipe for target 'src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/all' failed
make[1]: *** [src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nibio74** [comment] 2018-05-06 17:54
This is my file .out 
[ccA5tslK.out.txt](https://github.com/gerstrong/Commander-Genius/files/1977870/ccA5tslK.out.txt)

**Comment by gerstrong** [comment] 2018-05-08 06:10
No, same problem. Can you update gcc 4.8 to something more recent?

**Comment by gerstrong** [comment] 2018-05-08 06:13
duplicate of  #341

**Closed** 2018-05-27 07:14 UTC
