### ISSUE TITLE
Retropie build: CGeniusExe not found

### ISSUE THREAD

**Issue by vinzz73** [gerstrong/Commander-Genius#258] opened 2016-08-20 12:28 UTC
When building from the Retropie menu (basically a manual build within Retropie) following error occurs:

`Could not successfully install Commander Genius - Modern Interpreter for the Commander Keen Games (Vorticon and Galaxy Games) (/home/pi/RetroPie-Setup/tmp/build/cgenius/src/Build/LINUX/CGeniusExe not found).`

I know I probably must place a game binary somewhere but in the documentation I can't find a lead on where or how to do so. 

However a couple of log rules earlier it says:

`‘/home/pi/RetroPie-Setup/tmp/build/cgenius/vfsroot/games/keen7/KEEN4E.EXE’ -> ‘/opt/retropie/ports/cgenius/games/keen7/KEEN4E.EXE’
`

Help greatly appreciated.

**Comment by gerstrong** [comment] 2016-08-28 11:36
I have no idea about Retropie but it seems that you did not "make install" but make instead. Can you show me how you performed your setup?

**Comment by Arithmeticae** [comment] 2016-09-05 14:27
The setup script that build Command Genius for the retropie can be found [here](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/ports/cgenius.sh).

The relevant code section looks like:
`function build_cgenius() {`
`    cd $md_build`
`    cmake -DUSE_SDL2=yes -DCMAKE_INSTALL_PREFIX="$md_inst"`
`    make`
`    md_ret_require="$md_build"`
`}`

I hope that helps, and if you need something else I am happy to help.

**Comment by latschmahal** [comment] 2016-09-11 20:44
Hi,
I'm facing probably the same issue! The error I get in the end is the same, but the reason is that during compilation an error occurs.

```
[ 90%] Building CXX object src/fileio/compression/CMakeFiles/fileio_compression.dir/CCarmack.cpp.o
In file included from /home/pi/RetroPie-Setup/tmp/build/cgenius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.cpp:8:0:
/home/pi/RetroPie-Setup/tmp/build/cgenius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h: In member function ‘virtual void galaxy::CVarPlatform::_ZTv0_n112_N6galaxy12CVarPlatform9serializeER19CSaveGameController(CSaveGameController&)’:
/home/pi/RetroPie-Setup/tmp/build/cgenius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h:37:10: internal compiler error: Segmentation fault
     void serialize(CSaveGameController &savedGame)
```

I don't know right now why this error occurs, maybe someone have an idea?!
Find attached the full log.

[rps_2016-09-11_153624.txt](https://github.com/gerstrong/Commander-Genius/files/466229/rps_2016-09-11_153624.txt)

**Comment by superjamie** [comment] 2016-10-08 06:59
Duplicate of https://github.com/gerstrong/Commander-Genius/issues/254

**Closed** 2017-02-09 16:35 UTC

**Comment by ronilaukkarinen** [comment] 2018-01-09 19:43
Fixed this issue by `sudo apt-get install libpython3.4-dev libpython3.4`. After this, building just fine. 

Traced this by testing command by command and noticed for some reason retroarch didn't have latest python libraries installed, thus leading to CMake Error with PYTHON_LIBRARY variable.

**Comment by gerstrong** [comment] 2018-01-10 14:43
Thanks. I always tested this against Python 3.5 but good to know 3.4 also does it.

**Comment by bigblockentmt** [comment] 2018-08-28 21:04
Has anyone tried Commander Keen on the SUMOSYS? Cant get it to work
